services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: dsp_user
      POSTGRES_PASSWORD: dsp_pass
      POSTGRES_DB: dsp_db
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "
        python manage.py makemigrations submissions &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A dsp_integration.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  beat:
    build: .
    command: celery -A dsp_integration.celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
