# Generated by Django 5.2.4 on 2025-07-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dspentityqueue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], default='waiting', max_length=10),
        ),
    ]
