# Generated by Django 5.2.4 on 2025-07-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_dspentityqueue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dspentityaudit',
            name='backoff_secs',
        ),
    ]
